version: '3.8'

services:
  backend:
    build:
      context: ./surfsense_backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"    # تغيير المنفذ الخارجي إلى 8001
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/surfsense
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - UNSTRUCTURED_API_KEY=${UNSTRUCTURED_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    networks:
      - surfsense_network

  frontend:
    build:
      context: ./surfsense_web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
    depends_on:
      - backend
    networks:
      - surfsense_network

  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=surfsense
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - surfsense_network

volumes:
  postgres_data:

networks:
  surfsense_network:
    driver: bridge
